### ISSUE TITLE
Remettre la valeur par défaut de text-rendering ?

### ISSUE THREAD

**Issue by raphaelgoetter** [tzi/ChewingGrid#1]
Hello,

Dans ton fichier `/src/mixins/core/_cell.core.scss`, tu appliques un reset des propriétés de inline-block.

Par contre, tu laisses `text-rendering` à sa valeur `optimizelegibility`, ce serait peut-être mieux de la resetter aussi à `auto`, non ?

**Comment by tzi** [comment]
Salut @raphaelgoetter !

En effet, c'est une erreur de ma part ;)
Merci Je corrige ça.

Trouves-tu le concept de cette grille utile ?
As-tu d'autre remarques ?

A bientôt,
Thomas.

**Comment by raphaelgoetter** [comment]
> Trouves-tu le concept de cette grille utile ?
> As-tu d'autre remarques ?

C'est un peu compliqué, parce que chacun aujourd'hui dispose de sa grille et y trouve son bonheur.

Du coup, chez nous on a opté pour une grille au nommage simplissime (c'est uniquement le conteneur qui a une classe, pas ses enfants sauf exception), je suis peu fan des cumuls "row" + "cell" + "card".
Mais ta grille a l'avantage d'être un peu plus polyvalente.

Et le rajout de markup "ghost" n'est pas très sexy non plus.

Mais je vais forcément trouver des défauts à ta grille, tout bêtement : 
- parce que je ne l'ai pas testée
- parce qu'on a déjà adopté la notre et qu'on s'y est habitués ;)

**Comment by tzi** [comment]
Merci Raphaël d'y mettre les formes :)

> C'est un peu compliqué, parce que chacun aujourd'hui dispose de sa grille et y trouve son bonheur.

En effet, j'ai aussi ma grille préférée.
J'utilise celle-ci en complément pour des cas très particulier, principalement le card listing.
Dans les autres cas, je préfère une grille plus précise, basé sur du partage de largeur (+ media-query) plutôt que sur les contraintes de tailles.

> Et le rajout de markup "ghost" n'est pas très sexy non plus.

100% d'accord. 
Du coup, ce n'est pas super scalable non-plus.
Je n'ai pas trouvé de solution pour ne pas les avoir pour l'instant.

Merci en tout cas pour tes retours !
Ça me fait plaisir :)

A plus,
Thomas.

**Comment by raphaelgoetter** [comment]
> Je n'ai pas trouvé de solution pour ne pas les avoir pour l'instant.

En flexbox c'est facile, mais avec ton fallback inline-block c'est tout de suite moins drôle :/

**Comment by tzi** [comment]
Hein ?
Les cellules ghost ne servent que pour `flexbox`, pour limiter l'expansion de la dernière ligne.
Alors que le fallback en `inline-block` prennent toujours la taille de leur contenu.

Tu pensais à quoi pour s'en priver avec `flexbox` ?

**Comment by raphaelgoetter** [comment]
Pour moi, je ne vois la nécessité de de ghosts qu'à partir du moment où tu es en `justify-content: space-between`, sinon ça donne ça de base : 
http://codepen.io/raphaelgoetter/pen/mzKrh?editors=110 (supprime l'offset du margin-left: auto sur le dernier item).

**Comment by tzi** [comment]
Dans ton cas, cela fonctionne parce que tes cellules ont `flex-grow` à 0.

J'ai modifié ton pen pour mettre un `min-width` et déclancher le retour à la ligne.
C'est le but de cette grille, ne pas avoir déclarer les changements de tailles de la grille : http://codepen.io/tzi/pen/MwQxao?editors=110

Du coup, dès qu'on est plus avec le nombre maximum de colonnes, les cases sont limitées à leur largeur minimum, et on peu perdre pas mal d'espace : 

![flexbox-without-flex-grow](https://cloud.githubusercontent.com/assets/415891/8501202/78fc0d54-21a3-11e5-81c3-c2542db26614.png)

**Comment by raphaelgoetter** [comment]
OK je comprends mieux la situation en tenant compte que tu n'utilises pas de MQ en effet, ça change tout ;)

**Comment by tzi** [comment]
Ahhh :)
Penses-tu que je peux faire quelque chose pour que son but soit plus explicite ?
Par exemple, modifier la description du projet ou ajouter un paragraphe sur les cas d'usages ?

Merci pour tes retours.
Thomas.

**Comment by raphaelgoetter** [comment]
Il est vrai que le fonctionnement, et l'objectif, ne m'avaient pas immédiatement sautés aux yeux.

Je ne serais pas contre un peu plus d'explications en effet.

**Comment by tzi** [comment]
Salut @raphaelgoetter !

J'ai réécrit la description.
Est-ce que tu trouves ça plus compréhensible ?

Merci :)

**Comment by raphaelgoetter** [comment]
C'est parfait comme ça, l'image est très parlante, bien vu !

**Comment by bsitruk** [comment]
Je ne suis pas sûre d'avoir compris à quelle problématique repond cette grille ?
Pourrais-tu me l'expliquer ?

EDIT: OK, je pense y voir un peu plus clair.
Je venai juste de lire cette article: http://tympanus.net/codrops/2015/04/15/grid-item-animation-layout/
Je pense que ta grille aurait parfaitement convenu ici !

EDIT: Sauf que sur ce lien, il aurait mis une min-width sur les items, et un flex-grow:1, le resultat aurait été quasi-identique.

**Comment by tzi** [comment]
Salut @bsitruk !

En effet, chewing-grid aurait été très bien pour refaire l'effet de la démo codrops ;)
Ils s'auraient évité des media-queries !

Pour être franc, cette grille peut être écrite en quelques lignes.
`min-width` et `flex-grow` représente en gros la moitié :P 

La valeur de ce projet réside plutôt dans : 
1. **Les tests** : Cette grille a été testée sous plusieurs versions d'IE et de Safari par exemple. Après ce projet, je pense que ce genre d'usage "poussé" de flexbox est vraiment compliqué et tu ne peux pas juste espéré que les navigateurs vont rendre correctement.
2. **Le fallback** : Cette grille contient plus de lignes de code pour implémenter le style quand flexbox n'est pas supporté que l'inverse. 
3. **La documentation**, c'est toujours mieux qu'un code maison...
