### ISSUE TITLE
Does this replace Herow?

### ISSUE THREAD

**Issue by visualcookie** [tzi/ChewingGrid#2]
Hi,

I'm asking, if this replaces Herow. Just discovered Herow and I quite like it so far. Is this the same as Herow and Herow has become deprecated?

**Comment by tzi** [comment]
Hi @visualcookie!

I'm really glad you like Herow.
Please, don't hesitate to send me feedbacks on it or to share website done with it ;)
I have a lot of work to do to improve the documentation. Some really nice feature are a hidden for now.

**Herow and chewing-grid are two complementary tools:**
- with Herow, you determine the size of a cell from the window size (media-queries) ;
- chewing-grid, you determine the size of a cell from the parent size and the minimum width the cell could take. 

When Herow is a great tool for layout, chewing-grid is a great tool for tiles, product listing, or card design. 

chewing-grid is easy to use, easy to reuse (doesn't depend of its context) and fit more with the design logic! But it comes with some constraints:
- Not predictive as media-queries oriented grids
- Every cells have always the same width
- Every cells have the height of its row
- etc.

chewing-grid is a great tool. But it should be use for some limited use cases, where it simpler than a media-query oriented grid. For the other cases, I recommend Herow, obviously ;)

Cheers,
Thomas.
