### ISSUE TITLE
little typos

### ISSUE THREAD

**Issue by raphaelgoetter** [tzi/ChewingGrid#3]
Hello Thomas,

There's a little error in the doc at _2.E. Set a maximum card width_ section : 

The example says `chew-row chew-row--card-min-500` but should be `chew-row chew-row--card-max-500`

Further, at _3.C. Limit the column number_ you tell : 

> Change the cell flex-basis and the width to set a column limit

But the example only changes `width` value. Do we have to change `flex-basis` too ?

Have a nice day ;)

**Comment by tzi** [comment]
Hi Raphael!

Thanks for your help and your attention!

I removed the use of `flex-basis` to set the column limit, because [IE 10-11 doesn't account for box-sizing:border-box](https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box).

Cheers,
Thomas.
